import JQuery from 'jquery/src/jquery'
import bootstrapjs from 'bootstrap/dist/js/bootstrap.js' 
import bootstrap from 'bootstrap/dist/css/bootstrap.css'
import bootstrapMaterial from 'bootstrap-material-design/dist/css/bootstrap-material-design.css'
import ripplesCss from 'bootstrap-material-design/dist/css/ripples.css'
import bootstrapMaterialJs from 'bootstrap-material-design/dist/js/material.js'
import ripplesJs from 'bootstrap-material-design/dist/js/ripples.js'
import flagIconCss from 'flag-icon-css/css/flag-icon.css'